// MCP Router Core - FFI Header
// Auto-generated by cbindgen, do not edit manually

#ifndef MCP_ROUTER_CORE_H
#define MCP_ROUTER_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error code indicating a forward to meta tool is needed
 * Using -32000 (server-defined error range: -32000 to -32099)
 */
#define FORWARD_TO_META_TOOL -32000

/**
 * Opaque handle to the router
 */
typedef struct McpRouterHandle McpRouterHandle;

/**
 * Callback type for async tool calls
 * - context: opaque pointer passed back to Swift (e.g., continuation)
 * - success: true if call succeeded
 * - result_json: JSON string of result (null if failed)
 * - error_message: error message (null if succeeded)
 *
 * NOTE: Strings are valid only during callback. Swift must copy if needed.
 */
typedef void (*McpToolCallback)(void *context,
                                bool success,
                                const char *result_json,
                                const char *error_message);

/**
 * Create a new router instance
 */
struct McpRouterHandle *mcp_router_create(void);

/**
 * Destroy the router instance
 */
void mcp_router_destroy(struct McpRouterHandle *handle);

/**
 * Free a string returned by the library
 */
void mcp_router_free_string(char *s);

/**
 * Add an HTTP server configuration
 * Returns true on success, false on failure (error message in out_error)
 */
bool mcp_router_add_http_server(struct McpRouterHandle *handle,
                                const char *name,
                                const char *url,
                                const char *description,
                                char **out_error);

/**
 * Add a stdio server configuration (JSON format)
 */
bool mcp_router_add_server_json(struct McpRouterHandle *handle, const char *json, char **out_error);

/**
 * Load servers from JSON array
 */
bool mcp_router_load_servers_json(struct McpRouterHandle *handle,
                                  const char *json,
                                  char **out_error);

/**
 * Load workspaces from JSON array
 */
bool mcp_router_load_workspaces_json(struct McpRouterHandle *handle,
                                     const char *json,
                                     char **out_error);

/**
 * List all servers as JSON array
 */
char *mcp_router_list_servers(struct McpRouterHandle *handle);

/**
 * Remove a server by name
 */
bool mcp_router_remove_server(struct McpRouterHandle *handle, const char *name, char **out_error);

/**
 * Set server enabled/disabled and persist to servers.json
 */
bool mcp_router_set_server_enabled(struct McpRouterHandle *handle,
                                   const char *name,
                                   bool enabled,
                                   char **out_error);

/**
 * Set server flatten mode and persist to servers.json
 */
bool mcp_router_set_server_flatten_mode(struct McpRouterHandle *handle,
                                        const char *name,
                                        bool flatten,
                                        char **out_error);

/**
 * Set expose management tools (Light/Full mode)
 * - false = Light mode (basic tools only)
 * - true = Full mode (includes add_server, remove_server, update_server)
 */
bool mcp_router_set_expose_management_tools(struct McpRouterHandle *handle,
                                            bool expose,
                                            char **out_error);

/**
 * Get current expose management tools setting
 */
bool mcp_router_get_expose_management_tools(struct McpRouterHandle *handle);

/**
 * Get router status as JSON
 */
char *mcp_router_get_status(struct McpRouterHandle *handle);

/**
 * Start the HTTP server
 */
bool mcp_router_start_server(struct McpRouterHandle *handle, uint16_t port, char **out_error);

/**
 * Stop the HTTP server
 */
bool mcp_router_stop_server(struct McpRouterHandle *handle, char **out_error);

/**
 * Initialize logging (call once at startup)
 * Only shows WARN+ for mcp_router_core, silences other crates
 */
void mcp_router_init_logging(void);

/**
 * Get version string
 */
char *mcp_router_version(void);

/**
 * Call a tool asynchronously
 *
 * This function returns immediately. The callback will be invoked on completion.
 * The callback is called from a background thread - Swift must dispatch to main if needed.
 *
 * Parameters:
 * - handle: Router handle
 * - server_name: Name of the server (e.g., "lsp")
 * - tool_name: Name of the tool (e.g., "lsp_goto_definition")
 * - arguments_json: JSON string of tool arguments
 * - workspace_token: Optional workspace token (can be null for default)
 * - timeout_secs: Timeout in seconds (0 = default 120s)
 * - callback: Function to call on completion
 * - context: Opaque pointer passed to callback (typically Swift continuation)
 * - out_error: Receives error message if function returns false
 *
 * Returns: true if async call was started, false if setup failed
 */
bool mcp_router_call_tool_async(struct McpRouterHandle *handle,
                                const char *server_name,
                                const char *tool_name,
                                const char *arguments_json,
                                const char *workspace_token,
                                uint32_t timeout_secs,
                                McpToolCallback callback,
                                void *context,
                                char **out_error);

/**
 * List tools for a server asynchronously
 *
 * Similar to call_tool_async, returns immediately and invokes callback on completion.
 */
bool mcp_router_list_tools_async(struct McpRouterHandle *handle,
                                 const char *server_name,
                                 const char *workspace_token,
                                 uint32_t timeout_secs,
                                 McpToolCallback callback,
                                 void *context,
                                 char **out_error);

/**
 * Load settings from ~/.vimo/mcp-router/settings.json
 * Returns JSON string on success (caller must free), null on failure
 */
char *mcp_router_load_settings(char **out_error);

/**
 * Save settings to ~/.vimo/mcp-router/settings.json
 */
bool mcp_router_save_settings(const char *json, char **out_error);

/**
 * Load workspaces from ~/.vimo/mcp-router/workspaces.json into router
 */
bool mcp_router_load_workspaces_from_file(struct McpRouterHandle *handle, char **out_error);

/**
 * Save workspaces from router to ~/.vimo/mcp-router/workspaces.json
 */
bool mcp_router_save_workspaces_to_file(struct McpRouterHandle *handle, char **out_error);

/**
 * Check if mcp-router is installed in ~/.claude.json
 */
bool mcp_router_is_installed_to_claude_global(char **out_error);

/**
 * Install mcp-router to ~/.claude.json
 */
bool mcp_router_install_to_claude_global(uint16_t port, char **out_error);

/**
 * Uninstall mcp-router from ~/.claude.json
 */
bool mcp_router_uninstall_from_claude_global(char **out_error);

/**
 * Load servers from ~/.claude.json into router
 */
bool mcp_router_load_servers_from_claude_config(struct McpRouterHandle *handle, char **out_error);

/**
 * Load servers from ~/.vimo/mcp-router/servers.json into router (appends to existing)
 */
bool mcp_router_load_servers_from_router_config(struct McpRouterHandle *handle, char **out_error);

/**
 * Load servers from ~/.vimo/mcp-router/servers.json
 * Also auto-migrates from SwiftData if servers.json doesn't exist
 * NOTE: ~/.claude.json is NOT read here - Claude Code reads it directly
 */
bool mcp_router_load_all_servers(struct McpRouterHandle *handle, char **out_error);

/**
 * Add server to both router and config file
 * target: "global" or "project:/path/to/project"
 */
bool mcp_router_add_server_and_persist(struct McpRouterHandle *handle,
                                       const char *json,
                                       const char *target,
                                       char **out_error);

/**
 * Remove server from both router and config file
 */
bool mcp_router_remove_server_and_persist(struct McpRouterHandle *handle,
                                          const char *name,
                                          const char *target,
                                          char **out_error);

/**
 * Install mcp-router to project .mcp.json
 */
bool mcp_router_install_to_project(const char *project_path,
                                   const char *token,
                                   uint16_t port,
                                   char **out_error);

/**
 * Uninstall mcp-router from project .mcp.json
 */
bool mcp_router_uninstall_from_project(const char *project_path, char **out_error);

/**
 * Get workspace token from project .mcp.json
 * Returns token string or null if not found
 */
char *mcp_router_get_project_token(const char *project_path, char **out_error);

#endif  /* MCP_ROUTER_CORE_H */
