// MCP Router Core - FFI Header
// Auto-generated by cbindgen, do not edit manually

#ifndef MCP_ROUTER_CORE_H
#define MCP_ROUTER_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to the router
 */
typedef struct McpRouterHandle McpRouterHandle;

/**
 * Create a new router instance
 */
struct McpRouterHandle *mcp_router_create(void);

/**
 * Destroy the router instance
 */
void mcp_router_destroy(struct McpRouterHandle *handle);

/**
 * Free a string returned by the library
 */
void mcp_router_free_string(char *s);

/**
 * Add an HTTP server configuration
 * Returns true on success, false on failure (error message in out_error)
 */
bool mcp_router_add_http_server(struct McpRouterHandle *handle,
                                const char *name,
                                const char *url,
                                const char *description,
                                char **out_error);

/**
 * Add a stdio server configuration (JSON format)
 */
bool mcp_router_add_server_json(struct McpRouterHandle *handle, const char *json, char **out_error);

/**
 * Load servers from JSON array
 */
bool mcp_router_load_servers_json(struct McpRouterHandle *handle,
                                  const char *json,
                                  char **out_error);

/**
 * Load workspaces from JSON array
 */
bool mcp_router_load_workspaces_json(struct McpRouterHandle *handle,
                                     const char *json,
                                     char **out_error);

/**
 * List all servers as JSON array
 */
char *mcp_router_list_servers(struct McpRouterHandle *handle);

/**
 * Remove a server by name
 */
bool mcp_router_remove_server(struct McpRouterHandle *handle, const char *name, char **out_error);

/**
 * Set server enabled/disabled
 */
bool mcp_router_set_server_enabled(struct McpRouterHandle *handle,
                                   const char *name,
                                   bool enabled,
                                   char **out_error);

/**
 * Set server flatten mode
 */
bool mcp_router_set_server_flatten_mode(struct McpRouterHandle *handle,
                                        const char *name,
                                        bool flatten,
                                        char **out_error);

/**
 * Set expose management tools (Light/Full mode)
 * - false = Light mode (basic tools only)
 * - true = Full mode (includes add_server, remove_server, update_server)
 */
bool mcp_router_set_expose_management_tools(struct McpRouterHandle *handle,
                                            bool expose,
                                            char **out_error);

/**
 * Get current expose management tools setting
 */
bool mcp_router_get_expose_management_tools(struct McpRouterHandle *handle);

/**
 * Get router status as JSON
 */
char *mcp_router_get_status(struct McpRouterHandle *handle);

/**
 * Start the HTTP server
 */
bool mcp_router_start_server(struct McpRouterHandle *handle, uint16_t port, char **out_error);

/**
 * Stop the HTTP server
 */
bool mcp_router_stop_server(struct McpRouterHandle *handle, char **out_error);

/**
 * Initialize logging (call once at startup)
 * Only shows WARN+ for mcp_router_core, silences other crates
 */
void mcp_router_init_logging(void);

/**
 * Get version string
 */
char *mcp_router_version(void);

#endif  /* MCP_ROUTER_CORE_H */
